namespace System.Drawing.Imaging;

[System.ComponentModel.EditorAttribute("System.Drawing.Design.MetafileEditor, System.Drawing.Design, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", "System.Drawing.Design.UITypeEditor, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
public sealed partial class Metafile : System.Drawing.Image
{
	public Metafile(nint henhmetafile, bool deleteEmf) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(nint referenceHdc, System.Drawing.Imaging.EmfType emfType) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(nint referenceHdc, System.Drawing.Imaging.EmfType emfType, string? description) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(nint hmetafile, System.Drawing.Imaging.WmfPlaceableFileHeader wmfHeader) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(nint hmetafile, System.Drawing.Imaging.WmfPlaceableFileHeader wmfHeader, bool deleteWmf) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(nint referenceHdc, System.Drawing.Rectangle frameRect) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(nint referenceHdc, System.Drawing.Rectangle frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(nint referenceHdc, System.Drawing.Rectangle frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit, System.Drawing.Imaging.EmfType type) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(nint referenceHdc, System.Drawing.Rectangle frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit, System.Drawing.Imaging.EmfType type, string? desc) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(nint referenceHdc, System.Drawing.RectangleF frameRect) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(nint referenceHdc, System.Drawing.RectangleF frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(nint referenceHdc, System.Drawing.RectangleF frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit, System.Drawing.Imaging.EmfType type) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(nint referenceHdc, System.Drawing.RectangleF frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit, System.Drawing.Imaging.EmfType type, string? description) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(System.IO.Stream stream) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(System.IO.Stream stream, nint referenceHdc) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(System.IO.Stream stream, nint referenceHdc, System.Drawing.Imaging.EmfType type) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(System.IO.Stream stream, nint referenceHdc, System.Drawing.Imaging.EmfType type, string? description) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(System.IO.Stream stream, nint referenceHdc, System.Drawing.Rectangle frameRect) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(System.IO.Stream stream, nint referenceHdc, System.Drawing.Rectangle frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(System.IO.Stream stream, nint referenceHdc, System.Drawing.Rectangle frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit, System.Drawing.Imaging.EmfType type) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(System.IO.Stream stream, nint referenceHdc, System.Drawing.Rectangle frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit, System.Drawing.Imaging.EmfType type, string? description) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(System.IO.Stream stream, nint referenceHdc, System.Drawing.RectangleF frameRect) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(System.IO.Stream stream, nint referenceHdc, System.Drawing.RectangleF frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(System.IO.Stream stream, nint referenceHdc, System.Drawing.RectangleF frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit, System.Drawing.Imaging.EmfType type) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(System.IO.Stream stream, nint referenceHdc, System.Drawing.RectangleF frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit, System.Drawing.Imaging.EmfType type, string? description) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(string filename) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(string fileName, nint referenceHdc) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(string fileName, nint referenceHdc, System.Drawing.Imaging.EmfType type) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(string fileName, nint referenceHdc, System.Drawing.Imaging.EmfType type, string? description) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(string fileName, nint referenceHdc, System.Drawing.Rectangle frameRect) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(string fileName, nint referenceHdc, System.Drawing.Rectangle frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(string fileName, nint referenceHdc, System.Drawing.Rectangle frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit, System.Drawing.Imaging.EmfType type) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(string fileName, nint referenceHdc, System.Drawing.Rectangle frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit, System.Drawing.Imaging.EmfType type, string? description) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(string fileName, nint referenceHdc, System.Drawing.Rectangle frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit, string? description) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(string fileName, nint referenceHdc, System.Drawing.RectangleF frameRect) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(string fileName, nint referenceHdc, System.Drawing.RectangleF frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(string fileName, nint referenceHdc, System.Drawing.RectangleF frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit, System.Drawing.Imaging.EmfType type) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(string fileName, nint referenceHdc, System.Drawing.RectangleF frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit, System.Drawing.Imaging.EmfType type, string? description) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public Metafile(string fileName, nint referenceHdc, System.Drawing.RectangleF frameRect, System.Drawing.Imaging.MetafileFrameUnit frameUnit, string? desc) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public static System.Drawing.Imaging.MetafileHeader GetMetafileHeader(nint henhmetafile) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public static System.Drawing.Imaging.MetafileHeader GetMetafileHeader(nint hmetafile, System.Drawing.Imaging.WmfPlaceableFileHeader wmfHeader) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public static System.Drawing.Imaging.MetafileHeader GetMetafileHeader(System.IO.Stream stream) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public static System.Drawing.Imaging.MetafileHeader GetMetafileHeader(string fileName) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public nint GetHenhmetafile() { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public System.Drawing.Imaging.MetafileHeader GetMetafileHeader() { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
	public void PlayRecord(System.Drawing.Imaging.EmfPlusRecordType recordType, int flags, int dataSize, byte[] data) { throw new System.PlatformNotSupportedException("Not yet implemented in SkiaSharp.Extended.Drawing.Common"); }
}
