name: $(Date:yyyyMMdd).$(Rev:r)

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
      - CODE-OF-CONDUCT.md
      - LICENSE
      - .github/
      - docs/

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
      - CODE-OF-CONDUCT.md
      - LICENSE
      - .github/
      - docs/
      - images/

variables:
  - template: /scripts/azure-pipelines-variables.yml@self
  - name: OfficialBuildId
    value: $(Build.BuildNumber)

jobs:
  - template: /eng/common/templates/job/job.yml@self
    parameters:
      name: Build
      displayName: Build, test, and pack
      pool:
        vmImage: windows-latest
      runAsPublic: true
      timeoutInMinutes: 180
      enablePublishTestResults: true
      testResultsFormat: vstest
      testRunTitle: Unit Tests
      artifacts:
        publish:
          logs:
            name: BuildLogs
      preSteps:
        - checkout: self
          clean: true
          fetchDepth: 1
      steps:
        - template: /scripts/azure-pipelines-steps-prepare.yml@self
        - pwsh: >
            ./eng/common/build.ps1
            -restore -build -test -pack -publish
            -configuration $(_BuildConfig)
            -prepareMachine
            -warnNotAsError "CS0618;CS8600;CS8604;CS8605;CS8618;CS8622;CS8625;CS8767;XC0022;XC0025"
            -ci
            /p:OfficialBuildId=$(OfficialBuildId)
          displayName: Restore, build, test, pack, and publish manifests
