name: $(Date:yyyyMMdd).$(Rev:r)

trigger:
  branches:
    include:
      - main
      - release/*
  paths:
    exclude:
      - README.md
      - CODE-OF-CONDUCT.md
      - LICENSE
      - .github/
      - docs/

pr:
  branches:
    include:
      - main
      - release/*
  paths:
    exclude:
      - README.md
      - CODE-OF-CONDUCT.md
      - LICENSE
      - .github/
      - docs/
      - images/

variables:
  - template: /eng/common/templates/variables/pool-providers.yml@self
  - template: /scripts/azure-pipelines-variables.yml@self
  - name: OfficialBuildId
    value: $(Build.BuildNumber)

jobs:
  - template: /scripts/azure-pipelines-jobs-validation.yml@self
    parameters:
      pack: true
      platforms:
        Windows:
          os: windows
          pool:
            name: $(DncEngPublicBuildPool)
            demands: ImageOverride -equals windows.vs2026.amd64.open
          publish: true
          properties: ''
        macOS:
          os: macos
          pool:
            name: Azure Pipelines
            vmImage: macos-15
          publish: false
          properties: /p:EnableCodeSigning=false
        Linux:
          os: linux
          pool:
            name: $(DncEngPublicBuildPool)
            demands: ImageOverride -equals build.ubuntu.2204.amd64.open
          publish: false
          properties: ''
