<Project>
  <Import Project="Sdk.props" Sdk="Microsoft.DotNet.Arcade.Sdk" />

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <!-- Shipped assemblies have historically not been strong named. -->
    <SignAssembly>false</SignAssembly>
  </PropertyGroup>

</Project>
