<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsShipping>false</IsShipping>
    <TestRunnerName>XUnitV3</TestRunnerName>
    <UseVSTestRunner>true</UseVSTestRunner>
    <UseMicrosoftTestingPlatformRunner>false</UseMicrosoftTestingPlatformRunner>
    <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
    <ExcludeMicrosoftNetTestSdk>true</ExcludeMicrosoftNetTestSdk>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" PrivateAssets="all" Condition="$([MSBuild]::IsOSPlatform('linux'))" />
    <PackageReference Include="SkiaSharp.Skottie" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\source\SkiaSharp.Extended\SkiaSharp.Extended.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Update="images\**" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>