parameters:
  - name: buildAgentWindows
    type: object
  - name: useRealSigning
    type: boolean
    default: false
  - name: publishAssets
    type: boolean
    default: false

stages:
  - stage: package
    displayName: Build, pack, sign, and publish shipping products
    jobs:
      - template: /eng/common/templates-official/job/job.yml@self
        parameters:
          name: Build
          displayName: Build, pack, sign, and publish shipping products
          pool: ${{ parameters.buildAgentWindows.pool }}
          runAsPublic: false
          enableMicrobuild: true
          enableMicrobuildForMacAndLinux: false
          microbuildUseESRP: ${{ parameters.useRealSigning }}
          variables:
            - name: _SignType
              ${{ if eq(parameters.useRealSigning, true) }}:
                value: real
              ${{ else }}:
                value: test
          timeoutInMinutes: 180
          artifacts:
            publish:
              logs:
                name: BuildLogs
          preSteps:
            - checkout: self
              clean: true
              fetchDepth: 1
          steps:
            - template: /eng/pipelines/steps/setup.yml@self
              parameters:
                installWasmTools: false
            - template: /eng/pipelines/steps/pack.yml@self
              parameters:
                os: ${{ parameters.buildAgentWindows.pool.os }}
                publish: true
                sign: true
                signType: $(_SignType)

      - ${{ if eq(parameters.publishAssets, true) }}:
        - template: /eng/common/templates-official/job/publish-build-assets.yml@self
          parameters:
            dependsOn: Build
            runAsPublic: false
            publishingVersion: 3
            publishAssetsImmediately: false
            officialBuildId: $(ARCADE_OFFICIAL_BUILD_ID)
