using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using SkiaSharp;
using SkiaSharp.Drawing.Tests.Infrastructure;

namespace SkiaSharp.Drawing.Tests.PixelCompat;

/// <summary>
/// Compares SkiaSharp.Drawing output against reference images generated by real System.Drawing.
/// Reference images are expected in ReferenceImages/{Category}/{Name}.png
/// </summary>
public class ReferenceComparisonTests : PixelCompatibilityTestBase
{
    public static IEnumerable<object[]> AllScenarioData()
    {
        // Use the shared DrawingScenarios — same file compiled here via project reference
        foreach (var (name, category, _, _, _) in SkiaSharp.Drawing.Scenarios.DrawingScenarios.GetAll())
            yield return new object[] { name, category };
    }

    [Theory]
    [MemberData(nameof(AllScenarioData))]
    public void Scenario_MatchesReference(string name, string category)
    {
        var referenceFile = Path.Combine(category, $"{name}.png");
        var referencePath = Path.Combine(ReferenceImagesPath, referenceFile);

        if (!File.Exists(referencePath))
            Assert.Skip($"Reference image not found: {referencePath}. Run ReferenceGenerator on Windows first.");

        var scenario = SkiaSharp.Drawing.Scenarios.DrawingScenarios.GetAll()
            .First(s => s.Name == name);

        // Render with our SkiaSharp.Drawing — same code that the SkiaRunner uses
        using var bitmap = new Bitmap(scenario.Width, scenario.Height, PixelFormat.Format32bppArgb);
        using var graphics = Graphics.FromImage(bitmap);
        scenario.Draw(graphics);

        // Save to PNG bytes
        using var ms = new MemoryStream();
        bitmap.Save(ms, ImageFormat.Png);
        ms.Position = 0;

        using var actualBitmap = SKBitmap.Decode(ms);
        Assert.NotNull(actualBitmap);

        double tolerance = category switch
        {
            "Clear" or "Colors" => Tolerance_SolidFill,
            "Lines" or "Rectangles" => Tolerance_Stroke,
            "LinesAA" or "EllipsesAA" => Tolerance_AntiAliased,
            "Ellipses" or "Arcs" or "Pies" => Tolerance_Stroke,
            "Boundaries" => Tolerance_Stroke,
            "Polygons" => Tolerance_Stroke,
            "Composites" => Tolerance_AntiAliased,
            _ => Tolerance_AntiAliased,
        };

        AssertPixelCompatible(actualBitmap, referenceFile, tolerance, category);
    }
}
