using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using SkiaSharp;
using SkiaSharp.Drawing.Scenarios;
using SkiaSharp.Drawing.Tests.Infrastructure;

namespace SkiaSharp.Drawing.Tests.PixelCompat;

/// <summary>
/// Compares SkiaSharp.Drawing output against reference images generated by real System.Drawing.
/// Reference images are expected in ReferenceImages/{Category}/{Name}.png
/// </summary>
public class ReferenceComparisonTests : PixelCompatibilityTestBase
{
    public static IEnumerable<object[]> AllScenarioData()
    {
        var refDir = ReferenceImagesPath;
        if (!Directory.Exists(refDir))
            yield break;

        foreach (var categoryDir in Directory.GetDirectories(refDir))
        {
            var category = Path.GetFileName(categoryDir);
            foreach (var pngFile in Directory.GetFiles(categoryDir, "*.png"))
            {
                var name = Path.GetFileNameWithoutExtension(pngFile);
                yield return new object[] { name, category };
            }
        }
    }

    [Theory]
    [MemberData(nameof(AllScenarioData))]
    public void Scenario_MatchesReference(string name, string category)
    {
        var referenceFile = Path.Combine(category, $"{name}.png");
        var referencePath = Path.Combine(ReferenceImagesPath, referenceFile);

        if (!File.Exists(referencePath))
            Assert.Skip($"Reference image not found: {referencePath}");

        // Render with our SkiaSharp.Drawing by invoking the scenario
        var tmpDir = Path.Combine(TestArtifactsPath, "_render");
        Environment.SetEnvironmentVariable("SCENARIO_OUTPUT_PATH", tmpDir);

        // Find the scenario class and method
        var scenarioType = typeof(ScenarioBase).Assembly.GetTypes()
            .FirstOrDefault(t => t.Name == category && t.IsSubclassOf(typeof(ScenarioBase)));
        Assert.NotNull(scenarioType);

        var instance = (ScenarioBase)Activator.CreateInstance(scenarioType!)!;
        var method = scenarioType!.GetMethod(name);
        Assert.NotNull(method);
        method!.Invoke(instance, null);

        var actualPath = Path.Combine(tmpDir, category, $"{name}.png");
        Assert.True(File.Exists(actualPath), $"Scenario did not produce output: {actualPath}");

        using var actualBitmap = SKBitmap.Decode(actualPath);
        Assert.NotNull(actualBitmap);

        double tolerance = category switch
        {
            "Clear" or "Colors" => Tolerance_SolidFill,
            "Lines" or "Rectangles" or "Boundaries" => Tolerance_Stroke,
            "Ellipses" or "Arcs" or "Pies" or "Polygons" or "Composites" => Tolerance_Stroke,
            "LinesAA" or "EllipsesAA" or "ArcsAA" or "PiesAA" or "PolygonsAA" or "CompositesAA" => Tolerance_AntiAliased,
            _ => Tolerance_Stroke,
        };

        AssertPixelCompatible(actualBitmap, referenceFile, tolerance, category);
    }
}
