using SkiaSharp;
using SkiaSharp.Drawing.Scenarios;
using SkiaSharp.Drawing.Tests.Infrastructure;

namespace SkiaSharp.Drawing.Tests.PixelCompat;

/// <summary>
/// Compares SkiaSharp.Drawing output against reference images generated by real System.Drawing.
/// Reference images are expected in ReferenceImages/{Category}/{Name}.png
/// </summary>
public class ReferenceComparisonTests : PixelCompatibilityTestBase
{
    public static IEnumerable<object[]> AllScenarioData()
    {
        foreach (var scenario in AllScenarios.GetAll())
            yield return new object[] { scenario.Name, scenario.Category };
    }

    [Theory]
    [MemberData(nameof(AllScenarioData))]
    public void Scenario_MatchesReference(string name, string category)
    {
        var referenceFile = Path.Combine(category, $"{name}.png");
        var referencePath = Path.Combine(ReferenceImagesPath, referenceFile);

        // Skip gracefully when reference images aren't present (normal for local dev)
        if (!File.Exists(referencePath))
            Assert.Skip($"Reference image not found: {referencePath}. Run the ReferenceGenerator on Windows to create reference images.");

        var scenario = AllScenarios.GetAll().First(s => s.Name == name);

        // Render with our SkiaSharp.Drawing wrapper
        using var surface = new SkiaDrawingSurface(scenario.Width, scenario.Height);
        scenario.Draw(surface);
        var pngBytes = surface.SaveAsPng();

        using var actualBitmap = SKBitmap.Decode(pngBytes);
        Assert.NotNull(actualBitmap);

        // Determine tolerance based on category
        double tolerance = category switch
        {
            "Clear" or "Colors" => Tolerance_SolidFill,
            "Lines" or "Rectangles" => Tolerance_Stroke,
            "LinesAA" or "EllipsesAA" => Tolerance_AntiAliased,
            "Ellipses" or "Arcs" or "Pies" => Tolerance_Stroke,
            "Polygons" => Tolerance_Stroke,
            "Composites" => Tolerance_AntiAliased,
            _ => Tolerance_AntiAliased,
        };

        AssertPixelCompatible(actualBitmap, referenceFile, tolerance, category);
    }
}
