steps:

  - pwsh: ./scripts/infra/set-build-variables.ps1 -UpdateBuildNumber
    displayName: Configure package version identity

  - task: JavaToolInstaller@0
    displayName: Select JDK
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - pwsh: |
      Write-Host "JavaSdkDirectory is being set to: $env:JAVA_HOME"
      Write-Host "##vso[task.setvariable variable=JavaSdkDirectory]$env:JAVA_HOME"
    displayName: Set Java SDK Directory

  - task: UseDotNet@2
    displayName: Install .NET SDK
    inputs:
      packageType: 'sdk'
      version: $(DOTNET_VERSION)

  - pwsh: dotnet workload install maui
    displayName: Install MAUI workload

  - pwsh: dotnet workload install wasm-tools
    displayName: Install WASM tools workload

  - pwsh: dotnet tool restore
    displayName: Restore the dotnet tools
