<Project>

  <PropertyGroup>
    <PublicApiType Condition="'$(PublicApiType)' == '' And ('$(CI)' == 'true' Or '$(TF_BUILD)' == 'true' Or '$(ContinuousIntegrationBuild)' == 'true')">Validate</PublicApiType>
    <PublicApiType Condition="'$(PublicApiType)' == ''">Generate</PublicApiType>
    <PublicApiTarget Condition="$(TargetFramework.StartsWith('netstandard'))">netstandard</PublicApiTarget>
    <PublicApiTarget Condition="'$(PublicApiTarget)' == '' And '$(TargetPlatformIdentifier)' == ''">net</PublicApiTarget>
    <PublicApiTarget Condition="'$(PublicApiTarget)' == ''">net-$(TargetPlatformIdentifier.ToLower())</PublicApiTarget>
    <PublicApiDirectory>$(MSBuildProjectDirectory)/PublicAPI/$(PublicApiTarget)</PublicApiDirectory>
    <PublicApiShippedFile>$(PublicApiDirectory)/PublicAPI.Shipped.txt</PublicApiShippedFile>
    <PublicApiUnshippedFile>$(PublicApiDirectory)/PublicAPI.Unshipped.txt</PublicApiUnshippedFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="all" Condition="'$(PublicApiType)' == 'Validate'" />
    <PackageReference Include="Mono.ApiTools.MSBuildTasks" PrivateAssets="all" Condition="'$(PublicApiType)' == 'Generate'" />
    <AdditionalFiles Include="$(PublicApiShippedFile)" />
    <AdditionalFiles Include="$(PublicApiUnshippedFile)" />
  </ItemGroup>

  <Target Name="GeneratePublicApiFiles"
          AfterTargets="Build"
          Condition="'$(PublicApiType)' == 'Generate' And '$(TargetFramework)' != ''"
          Inputs="$(TargetPath)"
          Outputs="$(IntermediateOutputPath)GeneratePublicApiFiles.stamp">
    <ItemGroup>
      <_PublicApiFiles Include="$(PublicApiShippedFile)" />
      <_PublicApiFiles Include="$(PublicApiUnshippedFile)" />
    </ItemGroup>

    <MakeDir Directories="$(PublicApiDirectory)" />

    <WriteLinesToFile File="$(PublicApiShippedFile)" Lines="#nullable enable" Condition="!Exists('$(PublicApiShippedFile)')" />
    <WriteLinesToFile File="$(PublicApiUnshippedFile)" Lines="#nullable enable" Condition="!Exists('$(PublicApiUnshippedFile)')" />

    <GeneratePublicApiFiles Assembly="$(TargetPath)" Files="@(_PublicApiFiles)" ReferenceSearchPaths="@(ReferencePath)" />

    <Touch Files="$(IntermediateOutputPath)GeneratePublicApiFiles.stamp" AlwaysCreate="true" />
    <ItemGroup>
      <FileWrites Include="$(IntermediateOutputPath)GeneratePublicApiFiles.stamp" />
    </ItemGroup>
  </Target>

</Project>
