using SkiaSharp;
using SkiaSharp.Extended;

namespace SkiaSharp.Drawing.Tests.Infrastructure;

/// <summary>
/// Base class for pixel-compatibility tests that compare SkiaSharp.Drawing output
/// against reference images generated by real System.Drawing (GDI+).
/// </summary>
public abstract class PixelCompatibilityTestBase
{
    // Tolerance tiers for different rendering categories
    protected const double Tolerance_SolidFill = 0.001;      // 0.1%
    protected const double Tolerance_Stroke = 0.005;          // 0.5%
    protected const double Tolerance_AntiAliased = 0.01;      // 1.0%
    protected const double Tolerance_Text = 0.02;             // 2.0%
    protected const double Tolerance_Gradient = 0.01;         // 1.0%
    protected const double Tolerance_HatchPattern = 0.001;    // 0.1%
    protected const double Tolerance_Transform = 0.015;       // 1.5%

    /// <summary>
    /// Gets the path to reference images directory. Can be overridden via 
    /// REFERENCE_IMAGES_PATH environment variable (for CI).
    /// </summary>
    protected static string ReferenceImagesPath =>
        Environment.GetEnvironmentVariable("REFERENCE_IMAGES_PATH")
        ?? Path.Combine(AppContext.BaseDirectory, "ReferenceImages");

    /// <summary>
    /// Gets the path to test output artifacts directory for saving failure diffs.
    /// </summary>
    protected static string TestArtifactsPath
    {
        get
        {
            var path = Environment.GetEnvironmentVariable("TEST_ARTIFACTS_PATH")
                ?? Path.Combine(AppContext.BaseDirectory, "TestArtifacts");
            Directory.CreateDirectory(path);
            return path;
        }
    }

    /// <summary>
    /// Asserts that the actual bitmap matches the reference image within the specified tolerance.
    /// On failure, saves the actual image and a diff visualization as test artifacts.
    /// </summary>
    protected void AssertPixelCompatible(
        SKBitmap actual,
        string referenceImageName,
        double maxErrorPixelPercentage,
        string? category = null)
    {
        var referencePath = Path.Combine(ReferenceImagesPath, referenceImageName);
        
        if (!File.Exists(referencePath))
        {
            // Save actual as the reference for bootstrapping
            SaveBitmap(actual, Path.Combine(TestArtifactsPath, $"actual_{Path.GetFileName(referenceImageName)}"));
            Assert.Fail($"Reference image not found: {referencePath}. Actual image saved to TestArtifacts/.");
            return;
        }

        using var reference = SKBitmap.Decode(referencePath);
        Assert.NotNull(reference);
        
        var result = SKPixelComparer.Compare(actual, reference);

        if (result.ErrorPixelPercentage > maxErrorPixelPercentage)
        {
            // Save artifacts for debugging
            var baseName = Path.GetFileNameWithoutExtension(referenceImageName);
            SaveBitmap(actual, Path.Combine(TestArtifactsPath, $"{baseName}_actual.png"));
            SaveDiffImage(actual, reference, Path.Combine(TestArtifactsPath, $"{baseName}_diff.png"));

            Assert.Fail(
                $"Pixel compatibility failed for '{referenceImageName}'" +
                (category != null ? $" [{category}]" : "") +
                $": ErrorPixelPercentage={result.ErrorPixelPercentage:P4}" +
                $" (max={maxErrorPixelPercentage:P4})," +
                $" MAE={result.MeanAbsoluteError:F4}," +
                $" PSNR={result.PeakSignalToNoiseRatio:F2}dB");
        }
    }

    /// <summary>
    /// Creates a System.Drawing.Bitmap via our SkiaSharp.Drawing implementation,
    /// executes drawing operations, and returns the result as an SKBitmap for comparison.
    /// </summary>
    protected static SKBitmap RenderWithSkiaDrawing(int width, int height, Action<System.Drawing.Graphics> drawAction)
    {
        using var bitmap = new System.Drawing.Bitmap(width, height);
        using var graphics = System.Drawing.Graphics.FromImage(bitmap);
        drawAction(graphics);
        
        // Convert System.Drawing.Bitmap to SKBitmap
        // This will work once Bitmap is implemented; for now it throws PNSE
        return ConvertToSKBitmap(bitmap);
    }

    private static SKBitmap ConvertToSKBitmap(System.Drawing.Bitmap bitmap)
    {
        // Placeholder — will be implemented when Bitmap has real backing
        throw new NotImplementedException("ConvertToSKBitmap will be implemented with Bitmap backing store");
    }

    private static void SaveBitmap(SKBitmap bitmap, string path)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        using var image = SKImage.FromBitmap(bitmap);
        using var data = image.Encode(SKEncodedImageFormat.Png, 100);
        using var stream = File.OpenWrite(path);
        data.SaveTo(stream);
    }

    private static void SaveDiffImage(SKBitmap actual, SKBitmap reference, string path)
    {
        var width = Math.Max(actual.Width, reference.Width);
        var height = Math.Max(actual.Height, reference.Height);
        
        using var diff = new SKBitmap(width, height);
        for (int y = 0; y < height; y++)
        {
            for (int x = 0; x < width; x++)
            {
                var a = (x < actual.Width && y < actual.Height) ? actual.GetPixel(x, y) : SKColors.Transparent;
                var r = (x < reference.Width && y < reference.Height) ? reference.GetPixel(x, y) : SKColors.Transparent;

                if (a == r)
                {
                    diff.SetPixel(x, y, new SKColor(r.Red, r.Green, r.Blue, 64)); // dimmed match
                }
                else
                {
                    var errorMagnitude = (byte)Math.Min(255,
                        Math.Abs(a.Red - r.Red) + Math.Abs(a.Green - r.Green) + Math.Abs(a.Blue - r.Blue));
                    diff.SetPixel(x, y, new SKColor(255, 0, 0, errorMagnitude)); // red = error
                }
            }
        }
        SaveBitmap(diff, path);
    }
}
