<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>SkiaSharp.Extended.UI.Blazor</AssemblyName>
    <RootNamespace>SkiaSharp.Extended.UI.Blazor</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SkiaSharp.Extended.UI.Blazor</PackageId>
    <Title>Additional SkiaSharp controls for Blazor</Title>
    <Description>This package adds additional SkiaSharp controls and utilities for Blazor applications.</Description>
    <IsPackable>true</IsPackable>
    <IsShipping>true</IsShipping>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp.Views.Blazor" />
  </ItemGroup>

</Project>
